In [1]:
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
data = pd.read_csv('Sales-products.csv',index_col="SaleID")
sales_products_data = data.copy()
sales_products_data.head()

,RetailerCountry,OrderMethod,RetailerType,ProductLine,ProductType,Product,Year,Quarter,Revenue,Quantity,GrossMargin
SaleID,,,,,,,,,,,
SaleID_1,United States,Fax,Outdoors Shop,Personal Accessories,Cooking Gear,TrailChef Deluxe Cook Set,2018.0,Q1 2018,59728.66,491.0,0.357548
SaleID_2,United States,Fax,Outdoors Shop,Sports Equipment,Cooking Gear,TrailChef Double Flame,2018.0,Q1 2018,36050.32,254.0,0.484274
SaleID_3,United States,Fax,Outdoors Shop,NaN,Tents,Star Dome,2018.0,Q1 2018,90040.48,149.0,NaN
SaleID_4,United States,Fax,Outdoors Shop,NaN,Tents,Star Gazer 2,2018.0,Q1 2018,NaN,305.0,0.292938
SaleID_5,United States,NaN,Outdoors Shop,Personal Accessories,First Aid,Compact Relief Kit,2018.0,Q1 2018,NaN,182.0,0.610710

In [3]:
sales_products_data.tail()

,RetailerCountry,OrderMethod,RetailerType,ProductLine,ProductType,Product,Year,Quarter,Revenue,Quantity,GrossMargin
SaleID,,,,,,,,,,,
SaleID_1272,Spain,Sales visit,Outdoors Shop,Personal Accessories,Rope,Husky Rope 60,2020.0,Q3 2020,30916.50,173.0,0.298114
SaleID_1273,Spain,Sales visit,Outdoors Shop,Outdoor Protection,Climbing Accessories,Firefly Climbing Lamp,2020.0,Q3 2020,7536.29,193.0,0.445287
SaleID_1274,Spain,Sales visit,Outdoors Shop,Personal Accessories,Climbing Accessories,Firefly Charger,2020.0,Q3 2020,12306.48,238.0,0.568420
SaleID_1275,Spain,Sales visit,Outdoors Shop,Personal Accessories,Tools,Granite Axe,2020.0,Q3 2020,56499.00,1472.0,0.490667
SaleID_1276,Spain,Sales visit,Outdoors Shop,Camping Equipment,Tools,Granite Extreme,2020.0,Q3 2020,89427.00,1178.0,0.386895

In [4]:
sales_products_data.sort_index().sort_values(["Year"]) # sorting by SaleID column and then by Year

,RetailerCountry,OrderMethod,RetailerType,ProductLine,ProductType,Product,Year,Quarter,Revenue,Quantity,GrossMargin
SaleID,,,,,,,,,,,
SaleID_1,United States,Fax,Outdoors Shop,Personal Accessories,Cooking Gear,TrailChef Deluxe Cook Set,2018.0,Q1 2018,59728.66,491.0,0.357548
SaleID_563,Finland,Sales visit,Outdoors Shop,Personal Accessories,Tools,Granite Ice,2018.0,Q3 2018,20855.20,278.0,0.480782
SaleID_562,Finland,Sales visit,Outdoors Shop,Personal Accessories,Climbing Accessories,Granite Chalk Bag,2018.0,Q3 2018,3857.32,215.0,0.515440
SaleID_561,Finland,Sales visit,Outdoors Shop,Camping Equipment,Climbing Accessories,Firefly Rechargeable Battery,2018.0,Q3 2018,11367.52,1454.0,0.593072
SaleID_560,Finland,Sales visit,Outdoors Shop,Mountaineering Equipment,Climbing Accessories,Firefly Charger,2018.0,Q3 2018,16856.40,328.0,0.563981
...,...,...,...,...,...,...,...,...,...,...,...
SaleID_1165,United Kingdom,E-mail,Outdoors Shop,Mountaineering Equipment,Cooking Gear,TrailChef Canteen,2020.0,Q2 2020,10351.54,708.0,0.442454
SaleID_1166,United Kingdom,E-mail,Outdoors Shop,Camping Equipment,Cooking Gear,TrailChef Cook Set,2020.0,Q2 2020,49175.16,924.0,0.342656
SaleID_1158,Germany,Phone,Outdoors Shop,Personal Accessories,Climbing Accessories,Granite Pulley,2020.0,Q1 2020,20950.62,569.0,0.501170
SaleID_1220,Germany,E-mail,Sports Store,Sports Equipment,Cooking Gear,TrailChef Double Flame,2020.0,Q3 2020,27589.38,193.0,0.478817
SaleID_411,Australia,Web,Department Store,Mountaineering Equipment,Sleeping Bags,NaN,NaN,Q3 2018,42334.12,308.0,0.386902

In [5]:
sales_products_data.describe(include='all') # Getting a general understanding of all the columns

,RetailerCountry,OrderMethod,RetailerType,ProductLine,ProductType,Product,Year,Quarter,Revenue,Quantity,GrossMargin
count,1276,1271,1273,1273,1273,1272,1275.000000,1276,1260.000000,1273.000000,1250.000000
unique,21,7,8,5,21,143,NaN,10,NaN,NaN,NaN
top,United States,Web,Outdoors Shop,Personal Accessories,Cooking Gear,Venue,NaN,Q3 2018,NaN,NaN,NaN
freq,163,431,440,420,157,25,NaN,612,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,2018.427451,NaN,31416.916794,600.657502,0.459638
std,NaN,NaN,NaN,NaN,NaN,NaN,0.717596,NaN,51124.450625,977.723516,0.112575
min,NaN,NaN,NaN,NaN,NaN,NaN,2018.000000,NaN,0.000000,1.000000,0.058709
25%,NaN,NaN,NaN,NaN,NaN,NaN,2018.000000,NaN,7452.782500,108.000000,0.375364
50%,NaN,NaN,NaN,NaN,NaN,NaN,2018.000000,NaN,15997.400000,267.000000,0.462960
75%,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,39661.317500,643.000000,0.526765
max,NaN,NaN,NaN,NaN,NaN,NaN,2020.000000,NaN,944436.750000,13758.000000,0.780476

 ### Checking Data types

In [ ]:
sales_products_data.info() # get the metadata about the table. (6)Year must be changed to datetime.

In [24]:
#change each row to a string
sales_products_data["Year"] = sales_products_data["Year"].astype(str).apply(lambda x: x.split('.')[0])

In [25]:
type(sales_products_data["Year"])

pandas.core.series.Series

### Filling missing values
### OrderMethod Column

In [ ]:
sales_products_data.isnull().sum()

In [ ]:
sales_products_data["OrderMethod"].describe()

In [ ]:
sales_products_data["OrderMethod"].isna().sum()

In [ ]:
# Fill OrderMethod with top occurring object ie "Web"
sales_products_data["OrderMethod"] = sales_products_data["OrderMethod"].fillna("Web")
sales_products_data["OrderMethod"]

### Retailer Type

In [ ]:
sales_products_data["RetailerType"].describe()

In [ ]:
# Fill with top
sales_products_data["RetailerType"] = sales_products_data["RetailerType"].fillna("Outdoors Shop")
sales_products_data["RetailerType"]

### Product Line

In [ ]:
sales_products_data["ProductLine"].describe()

In [ ]:
# fill with top
sales_products_data["ProductLine"] = sales_products_data["ProductLine"].fillna("Personal Accessories")
sales_products_data["ProductLine"]

### Product Type

In [ ]:
sales_products_data["ProductType"].describe()

In [ ]:
sales_products_data["ProductType"].isnull().sum()

In [ ]:
# fill with top
sales_products_data["ProductType"] = sales_products_data["ProductType"].fillna("Cooking Gear")
sales_products_data["ProductType"]

In [ ]:
sales_products_data.columns

### Product

In [ ]:
sales_products_data["Product"].isna().sum()

In [ ]:
sales_products_data["Product"].describe()

In [ ]:
#Fill with top
sales_products_data["Product"] =  sales_products_data["Product"].fillna("Venue")
sales_products_data["Product"]

### Year

In [ ]:
sales_products_data.head()

In [ ]:
# fill with top
year_filler = sales_products_data.loc["SaleID_1", "Year"]

In [ ]:
sales_products_data["Year"] = sales_products_data["Year"].fillna(year_filler)

### Revenue, Quantity,GrossMargin

In [ ]:
# mean of each column
revFiller,quanFiller,grossFiller = sales_products_data["Revenue"].mean(),sales_products_data["Quantity"].mean(),sales_products_data["GrossMargin"].mean()
revFiller,quanFiller,grossFiller

In [ ]:
# Fill each column with mean
sales_products_data["Revenue"] = sales_products_data["Revenue"].fillna(revFiller)
sales_products_data["Quantity"] = sales_products_data["Quantity"].fillna(quanFiller)
sales_products_data["GrossMargin"] = sales_products_data["GrossMargin"].fillna(grossFiller)

In [ ]:
sales_products_data[["Revenue","Quantity","GrossMargin"]]

In [ ]:
# Check for missing values
sales_products_data.isna().sum()

 ### Rename some columns

In [ ]:
new_column_names = ['Country', 'OrderMethod', 'Retailer', 'Line',
       'Type', 'Product', 'Year', 'Quarter', 'Revenue', 'Quantity',
       'Margin']
sales_products_data.columns = new_column_names
sales_products_data.columns

### Write to csv file

In [ ]:
sales_products_data.to_csv('newfile.csv', index=False)